/* Compute Shader for Particle System */
#version 430

// Taille du groupe de travail
layout(local_size_x = 256) in;

// Structures des données des particules
struct Particle {
    vec4 pos; // 16
    vec4 speed; // 16
    float age; // 4
    float ageMax; // 4
    vec4 color; // 16
    vec4 padding2;// 16
    vec4 padding3; // 16
    vec4 padding7; // 16
    vec4 padding8; // 16
    vec4 padding9; // 16
    // total : pos(16) + speed(16) + age(4) + ageMax(4) + color(16) +
    // padding2(16) + padding3(16) + padding7(16) + padding8(16) + padding9(16)
    // = 136 octect
    // wtf pk je dois pas mette cromme dnas particle.h




};

// Buffer des particules
layout(std430, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

// Uniformes
uniform float dt;

const vec3 gravity = vec3(0.0, 0.0, -9.8);

//fonction pour généré un nombre pseudo-aléatoire
float random(float seed) {
    return fract(sin(seed) * 43758.5453);
}

//fonction d'initialisation d'une particule
void initParticle(inout Particle p) {
    p.pos = vec4(0.0, 0.0, 0.0, 1.0); // Ajouter un w = 1.0 pour vec4
    float angle = 2.0 * 3.14159265359 * float(gl_GlobalInvocationID.x) / 256.0;
    float norm = 0.5 * random(float(gl_GlobalInvocationID.x));
    p.speed = vec4(norm * cos(angle), norm * sin(angle), 2.0 + random(float(gl_GlobalInvocationID.x) + 1.0) * 1.5, 0.0);
    p.age = 0.0;
    p.ageMax = 2.0 + random(float(gl_GlobalInvocationID.x) + 2.0) * 3.0;
    p.color = vec4(0.0, 0.0, 1.0, 1.0);
}

// Fonction principale
void main() {
    uint id = gl_GlobalInvocationID.x; // Identifiant unique de la particule

    // Récupérer la particule actuelle
    Particle p = particles[id];

    p.speed.xyz += gravity * dt;
    p.pos.xyz += p.speed.xyz * dt;

    // Gestion des rebonds
    if (p.pos.z < 0.0) {
        p.pos.z = 0.0;
        p.speed.z *= -0.6; // Coefficient de rebond
    }

    p.age += dt;

    // Réinitialiser la particule si elle dépasse son âge maximal
    if (p.age >= p.ageMax) {
        initParticle(p);
    }

    float lifeRatio = clamp(p.age / p.ageMax, 0.0, 1.0);
    p.color = mix(vec4(1.0, 0.0, 0.0, 1.0), vec4(0.0, 0.0, 1.0, 1.0), lifeRatio);

    particles[id] = p;
}